export const MESSAGE_TYPES = {
  GET_PAGE_CONTEXT: "GET_PAGE_CONTEXT",
  SCRAPE_CURRENT_PAGE: "SCRAPE_CURRENT_PAGE",
  APPEND_TO_AIRTABLE: "APPEND_TO_AIRTABLE",
  TEST_AIRTABLE_CONNECTION: "TEST_AIRTABLE_CONNECTION"
};

export const STORAGE_KEYS = {
  AIRTABLE_PAT: "airtablePat",
  AIRTABLE_BASE_ID: "airtableBaseId",
  AIRTABLE_TABLE_REF: "airtableTableRef"
};

export const ERROR_CODES = {
  UNSUPPORTED_PAGE: "UNSUPPORTED_PAGE",
  TABLE_NOT_FOUND: "TABLE_NOT_FOUND",
  TABLE_NOT_READY: "TABLE_NOT_READY",
  EMPTY_RESULTS: "EMPTY_RESULTS",
  MISSING_CONFIG: "MISSING_CONFIG",
  AIRTABLE_AUTH_ERROR: "AIRTABLE_AUTH_ERROR",
  AIRTABLE_SCHEMA_MISMATCH: "AIRTABLE_SCHEMA_MISMATCH",
  AIRTABLE_WRITE_PARTIAL: "AIRTABLE_WRITE_PARTIAL",
  NETWORK_ERROR: "NETWORK_ERROR"
};

export const PAGE_TYPES = {
  ORGANIZATIONS: "organizations",
  FUNDING_ROUNDS: "funding_rounds",
  ACQUISITIONS: "acquisitions",
  UNKNOWN: "unknown"
};

export const AIRTABLE_BASE_URL = "https://api.airtable.com";
export const AIRTABLE_BATCH_SIZE = 10;
export const AIRTABLE_BATCH_DELAY_MS = 225;

export const OPTIONAL_METADATA_FIELDS = {
  CRUNCHBASE_URL: "Crunchbase URL",
  SOURCE_PAGE_URL: "Source Page URL",
  SCRAPED_AT: "Scraped At"
};

export const SUPPORTED_HOST = "www.crunchbase.com";
